
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: marketplace-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: marketplace-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: marketplace-frontend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000

volumes:
  redis_data:
